### ISSUE TITLE
Callback if user rate the app or cancel the rating

### ISSUE THREAD

**Issue by namchuai** [britannio/in_app_review#1]
Thanks for the great library!

I would like to ask for a callback if user does rate the app or cancel the rating.

**Comment by britannio** [comment]
Unfortunately, the APIs that Android & IOS expose does not support this. In fact, if you exceed the quota or the user has already rated the app then there's no way to know if the pop-up was even shown to the user. This is by design to prevent spam or malicious use.

On IOS, you can show the pop-up three times within a 365-day period. On Android, it's not as clear.
https://developer.android.com/guide/playcore/in-app-review#quotas
