### ISSUE TITLE
Custom View UI and expose API to pass only the parameter values

### ISSUE THREAD

**Issue by rlazom** [britannio/in_app_review#29]
Could you think a way of just expose the API to pass the values as parameters in order to show a Custom View (Modal/Bottom Sheet/etc) and process the data manually?

**Comment by britannio** [comment]
@rlazom I don't think that what you're describing is possible with the underlying API's this plugin uses. Nonetheless, which "values" are you referring to? 

If you are trying to show a custom bottom sheet to get a gauge on how satisfied your users are then you can create your own widget to do so however it won't create an App Store/Play Store rating because such a system could easily be manipulated.
